### ISSUE TITLE
remove dependency on bitswap

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-blockservice#2]
The dependency on bitswap causes a dependency on libp2p. (really bitswap shouldnt depend on libp2p... but thats a story for another day). This means that things like unixfs has to depend on libp2p, because unixfs depends on merkledag which depends on this package.

These dependency chains existed while these packages were all bundled inside go-ipfs, but it was less apparent how ugly the dep tree was back then...

**Comment by whyrusleeping** [comment]
One option would be to define a set of interfaces in this package that bitswap implements, and just use those.

**Comment by Jorropo** [comment]
Only used in tests + both packages in the same repo now = not a problem.
